### ISSUE TITLE
LSST g band file is wrong

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/tdastro#127]
**Bug report**

LSST g band file looks different from others: wavelength range is different from others and all wavelengths are 4-digit, like they are in angstroms instead of being in nm.

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [ ] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [ ] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by hombit** [comment]
We should use "total" transmissions, for example this file should be used for g-band
https://github.com/lsst/throughputs/blob/22732801ff32be387de00b5888ccd3e0c787f422/baseline/total_g.dat

So we should also update other files to use total transmissions. Also, it would help to track it if we put this commit-specific links to the passbands README file

**Comment by OliviaLynn** [comment]
Thanks for bringing this to my attention! I must have copied/pasted the files over before, and there was some mismatch between the files from the old url and the new url.

I went ahead and replaced all the files (with the current url in use) in the test dir as part of #135

**Comment by hombit** [comment]
@hombit sounds great! Could you also check that other bands are from "total_*" files, not "filter_*"?

**Comment by OliviaLynn** [comment]
Checked and they are!
